In [1]:
import numpy as np

# creating arrays

In [3]:
d1=np.array([1,2,3])

In [6]:
d1[0]

np.int64(1)

In [8]:
d2=np.array([[4,5,6],[7,8,9]])

In [11]:
d2[0][0]

np.int64(4)

In [16]:
zero=np.zeros((3,3))

In [19]:
zero[0][0]

np.float64(0.0)

In [21]:
one=np.ones((3,3))
one[0][1]

np.float64(1.0)

In [22]:
eye=np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
lin=np.linspace(0,100,5)
lin

array([  0.,  25.,  50.,  75., 100.])

In [25]:
range=np.arange(0,100,5)
range

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [27]:
full=np.full((5,5),np.nan)
full

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [28]:
rand=np.random.randn(4,5)
rand

array([[ 3.79116444e-01,  1.77824846e-01, -4.02306661e-01,
        -8.22169319e-01,  5.28600558e-01],
       [-7.74273805e-01, -1.32972524e+00, -3.80204015e-01,
         6.31832126e-01,  1.75447357e+00],
       [-2.19000070e-01,  1.96001966e+00,  1.18398651e+00,
        -2.26579919e+00,  1.68043114e+00],
       [ 1.18121298e+00, -9.77479858e-01,  1.45055447e-03,
         2.27787283e+00,  9.27346785e-01]])

In [29]:
rand=np.random.rand(4,5)*100
rand

array([[ 7.12274415, 82.22592627, 31.12258029, 90.56541558, 95.10776697],
       [62.17323884, 22.86423517, 62.98462179,  9.06570769, 83.36584617],
       [50.93170519, 21.61600307, 84.30850826, 78.6072462 , 88.52262031],
       [27.17895316, 80.64684223, 30.86025109, 60.13581183, 82.01192014]])

In [32]:
randint=np.random.randint(5,size=(2,3))
randint

array([[1, 2, 0],
       [1, 2, 3]], dtype=int32)

In [33]:
randint.size

6

In [34]:
randint.shape

(2, 3)

In [35]:
randint.dtype

dtype('int32')

In [38]:
randint.tolist()

[[1, 2, 0], [1, 2, 3]]

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.info(np.eye(5))

class:  ndarray
shape:  (5, 5)
strides:  (40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x21c37893a10
byteorder:  little
byteswap:  False
type: float64
