In [3]:
import torch

In [4]:
import torch.nn as nn

In [5]:
torch.tensor([1,2,3])


tensor([1, 2, 3])

In [6]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])