In [3]:
import torch

In [4]:
import torch.nn as nn

In [5]:
torch.tensor([1,2,3])


tensor([1, 2, 3])

In [6]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
torch.linspace(0,100,6)

tensor([  0.,  20.,  40.,  60.,  80., 100.])

In [11]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [12]:
torch.full((2,3),8)

tensor([[8, 8, 8],
        [8, 8, 8]])