In [3]:
import torch

In [4]:
import torch.nn as nn

In [5]:
torch.tensor([1,2,3])


tensor([1, 2, 3])

In [6]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
torch.linspace(0,100,6)

tensor([  0.,  20.,  40.,  60.,  80., 100.])

In [11]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [12]:
torch.full((2,3),8)

tensor([[8, 8, 8],
        [8, 8, 8]])

In [13]:
torch.rand(4,5)

tensor([[0.0823, 0.5215, 0.2807, 0.0122, 0.9892],
        [0.0323, 0.6160, 0.9101, 0.1646, 0.3316],
        [0.2379, 0.8320, 0.1612, 0.5360, 0.1245],
        [0.3838, 0.8211, 0.1088, 0.5400, 0.9008]])

In [14]:
torch.randint(0,5,(2,3))

tensor([[2, 1, 0],
        [4, 3, 2]])

In [15]:
data=torch.randn(4,5)

In [16]:
data[0]

tensor([-0.1698,  1.3032, -0.6299, -0.4819,  1.1216])

In [18]:
data[0:2]

tensor([[-0.1698,  1.3032, -0.6299, -0.4819,  1.1216],
        [-0.8004, -0.6791, -1.0680,  1.5691, -0.8653]])

In [20]:
data[0:1,1]

tensor([1.3032])

In [22]:
data.numel()

20

In [23]:
data.shape

torch.Size([4, 5])