In [9]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [12]:
#dir(tf)

In [14]:
tensor=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [32]:
class TensorShowcase:
    def __init__(self):
        """Initialize the class with various tensor ranks."""
        # Rank 0: scalar
        self.rank_0 = tf.constant(4)

        # Rank 1: Vector
        self.rank_1 = tf.constant([1,2,3])

        # Rank 2: Matrix (3x3)
        self.rank_2 = tf.constant([[4,5,6], [7,8,9]], dtype=tf.int32)

        # Rank 3: 3D Tensor (2x2x2)
        self.rank_3 = tf.constant([
                                [[1,2], [3,4]],
                                [[5,6], [7,8]]
                                ], dtype=tf.int32)



    def display_shapes(self):
        """Method to print the shapes of all stored tensors."""
        print(f"Rank 0 Shape: {self.rank_0.shape} (Scalar)")
        print(f"Rank 1 Shape: {self.rank_1.shape} (Vector)")
        print(f"Rank 2 Shape: {self.rank_2.shape} (Tensor)")
        print(f"Rank 3 Shape: {self.rank_3.shape} (Tensor)")

    def create_tensor(self, rows, cols):
        shape=(rows, cols)

        random_tensor = tf.random.normal(shape=shape, mean=0, stddev=1)
        return random_tensor



tensor=TensorShowcase()
tensor.display_shapes()
tensor.create_tensor(2,3)


Rank 0 Shape: () (Scalar)
Rank 1 Shape: (3,) (Vector)
Rank 2 Shape: (2, 3) (Tensor)
Rank 3 Shape: (2, 2, 2) (Tensor)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.858368  ,  0.770671  ,  0.41996235],
       [ 0.76081   ,  0.7169302 , -1.6572577 ]], dtype=float32)>