In [9]:
import tensorflow as tf
from tensorflow.python.ops.init_ops_v2 import uniform

print(tf.__version__)

2.20.0


In [12]:
#dir(tf)

In [14]:
tensor=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [41]:
class TensorShowcase:
    def __init__(self):
        """Initialize the class with various tensor ranks."""
        # Rank 0: scalar
        self.rank_0 = tf.constant(4)

        # Rank 1: Vector
        self.rank_1 = tf.constant([1,2,3])

        # Rank 2: Matrix (3x3)
        self.rank_2 = tf.constant([[4,5,6], [7,8,9]], dtype=tf.int32)

        # Rank 3: 3D Tensor (2x2x2)
        self.rank_3 = tf.constant([
                                [[1,2], [3,4]],
                                [[5,6], [7,8]]
                                ], dtype=tf.int32)



    def display_shapes(self):
        """Method to print the shapes of all stored tensors."""
        print(f"Rank 0 Shape: {self.rank_0.shape} (Scalar)")
        print(f"Rank 1 Shape: {self.rank_1.shape} (Vector)")
        print(f"Rank 2 Shape: {self.rank_2.shape} (Tensor)")
        print(f"Rank 3 Shape: {self.rank_3.shape} (Tensor)")

    def create_tensor(self, rows, cols):
        shape=(rows, cols)

        random_tensor = tf.random.normal(shape=shape, mean=0, stddev=1)
        return random_tensor


    def zeros_create(self, rows, cols):
        shape=(rows, cols)
        zeros_tensor = tf.zeros(shape=shape, dtype=tf.float32)
        return zeros_tensor

    def ones_create(self, rows, cols):
        shape=(rows, cols)
        ones_tensor = tf.ones(shape=shape, dtype=tf.float32)
        return ones_tensor

    # Random uniform distribution between 0 and 10
    def create_uniform(self, rows, cols):
        shape=(rows, cols)
        uniform_tensor = tf.random.uniform(shape=shape, minval=0, maxval=1)
        return uniform_tensor


tensor=TensorShowcase()
tensor.display_shapes()
tensor.create_tensor(5,3)
tensor.zeros_create(5,3)
tensor.ones_create(5,3)
tensor.create_uniform(5,3)


Rank 0 Shape: () (Scalar)
Rank 1 Shape: (3,) (Vector)
Rank 2 Shape: (2, 3) (Tensor)
Rank 3 Shape: (2, 2, 2) (Tensor)


<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.8496561 , 0.8062178 , 0.78909695],
       [0.7348045 , 0.9507327 , 0.90467036],
       [0.05974472, 0.9422102 , 0.7414501 ],
       [0.2769568 , 0.7409191 , 0.3347087 ],
       [0.0220592 , 0.19379401, 0.87135017]], dtype=float32)>

In [44]:
# new class
class TensorOperations:
    def __init__(self):
        self.a=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
        self.b=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

    def addition(self):
        return self.a + self.b



operations=TensorOperations()
operations.addition()

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>