In [9]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [12]:
#dir(tf)

In [14]:
tensor=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [16]:
class Tensor:
    def __init__(self):
        """Initialize the class with various tensor ranks."""
        # Rank 0: scalar
        self.rank_0 = tf.constant(4)

