In [1]:
import tensorflow as tf
from keras.src.ops import append
from tensorflow.python.ops.init_ops_v2 import uniform

print(tf.__version__)

2.20.0


C:\Users\mdsan\Documents\python_project\OOPs_concept\.venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
#dir(tf)

In [3]:
tensor=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [4]:
class TensorShowcase:
    def __init__(self):
        """Initialize the class with various tensor ranks."""
        # Rank 0: scalar
        self.rank_0 = tf.constant(4)

        # Rank 1: Vector
        self.rank_1 = tf.constant([1,2,3])

        # Rank 2: Matrix (3x3)
        self.rank_2 = tf.constant([[4,5,6], [7,8,9]], dtype=tf.int32)

        # Rank 3: 3D Tensor (2x2x2)
        self.rank_3 = tf.constant([
                                [[1,2], [3,4]],
                                [[5,6], [7,8]]
                                ], dtype=tf.int32)



    def display_shapes(self):
        """Method to print the shapes of all stored tensors."""
        print(f"Rank 0 Shape: {self.rank_0.shape} (Scalar)")
        print(f"Rank 1 Shape: {self.rank_1.shape} (Vector)")
        print(f"Rank 2 Shape: {self.rank_2.shape} (Tensor)")
        print(f"Rank 3 Shape: {self.rank_3.shape} (Tensor)")

    def create_tensor(self, rows, cols):
        shape=(rows, cols)

        random_tensor = tf.random.normal(shape=shape, mean=0, stddev=1)
        return random_tensor


    def zeros_create(self, rows, cols):
        shape=(rows, cols)
        zeros_tensor = tf.zeros(shape=shape, dtype=tf.float32)
        return zeros_tensor

    def ones_create(self, rows, cols):
        shape=(rows, cols)
        ones_tensor = tf.ones(shape=shape, dtype=tf.float32)
        return ones_tensor

    # Random uniform distribution between 0 and 10
    def create_uniform(self, rows, cols):
        shape=(rows, cols)
        uniform_tensor = tf.random.uniform(shape=shape, minval=0, maxval=1)
        return uniform_tensor


tensor=TensorShowcase()
tensor.display_shapes()
tensor.create_tensor(5,3)
tensor.zeros_create(5,3)
tensor.ones_create(5,3)
tensor.create_uniform(5,3)


Rank 0 Shape: () (Scalar)
Rank 1 Shape: (3,) (Vector)
Rank 2 Shape: (2, 3) (Tensor)
Rank 3 Shape: (2, 2, 2) (Tensor)


<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.7920376 , 0.5341579 , 0.38837683],
       [0.40464938, 0.05865014, 0.25863898],
       [0.16516924, 0.10402179, 0.6603191 ],
       [0.82970583, 0.42669344, 0.20835721],
       [0.899956  , 0.7025621 , 0.7089149 ]], dtype=float32)>

In [5]:
# new class
class TensorOperations:
    def __init__(self):
        self.a=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
        self.b=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

    def addition(self):
        return self.a + self.b

    def subtraction(self):
        return self.a - self.b

    def multiplication(self):
        return self.a * self.b

    def division(self):
        return self.a / self.b


operations=TensorOperations()
operations.addition()
operations.subtraction()
operations.multiplication()
operations.division()

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])>

In [6]:
# convert numpy to tensor and vise versa
import numpy as np

class ConvertNumpyToTensor:
    def __init__(self):
        self.a=np.array([1,2,3])
        self.b=tf.constant([4,5,6])

    # Convert NumPy array to PyTorch Tensor
    def convert_tensor(self):
        tensor_from_numpy=tf.convert_to_tensor(self.a, dtype=tf.float32)
        return tensor_from_numpy

    def convert_to_numpy(self):
        tensor_to_numpy=np.array(self.b)
        return tensor_to_numpy


converter=ConvertNumpyToTensor()
converter.convert_tensor()
converter.convert_to_numpy()


array([4, 5, 6], dtype=int32)

In [22]:
class Calculation(TensorShowcase):
    def __init__(self):
        super().__init__()
        # Rank 4: 3D Tensor (2x2x2)
        self.rank_4 = tf.constant([
                                [[1,2], [3,4]],
                                [[5,6], [7,8]]
                                ], dtype=tf.int32)

    def addition(self):
        return self.rank_3 + self.rank_4
    def subtraction(self):
        return self.rank_3 - self.rank_4
    def multiplication(self):
        return self.rank_3 * self.rank_4

    @staticmethod
    def matrix_addition_example(self):
        c=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
        d=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
        return tf.add(c,d)




In [26]:
calculator=Calculation()
print(calculator.addition())
print(calculator.subtraction())
print(calculator.multiplication())
print(calculator.matrix_addition_example())

tf.Tensor(
[[[ 2  3]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[ 0 -1]
  [-2 -3]]

 [[-3 -4]
  [-5 -6]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[10 12]
  [14 16]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]], shape=(3, 3), dtype=int32)


In [24]:
import tensorflow as tf

class TensorShowcase:
    def __init__(self):
        # Rank 3 tensor (2x2x2)
        self.rank_3 = tf.constant([
            [[1, 1], [1, 1]],
            [[2, 2], [2, 2]]
        ], dtype=tf.int32)

class Calculation(TensorShowcase):
    def __init__(self):
        super().__init__()
        # Rank 4 tensor (2x2x2)
        self.rank_4 = tf.constant([
            [[1, 2], [3, 4]],
            [[5, 6], [7, 8]]
        ], dtype=tf.int32)

    # Operations using class attributes
    def addition(self):
        return self.rank_3 + self.rank_4

    def subtraction(self):
        return self.rank_3 - self.rank_4

    def multiplication(self):
        return self.rank_3 * self.rank_4

    # Independent matrix addition example
    @staticmethod
    def matrix_addition_example():
        a = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
        b = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
        return tf.add(a, b)


In [25]:
Calculation.matrix_addition_example()
print(Calculation.matrix_addition_example())


tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]], shape=(3, 3), dtype=int32)


In [13]:
class Series:
    def __init__(self,num):
        self.num=num

    def add_num(self):
        return self.num*(self.num+1)/2

    def add_square(self):
        sum=0
        for i in range(1,self.num):
            sum=sum+i**2
            print(sum)
        return sum

    def add_qube(self):
        sum=0
        for i in range(1,self.num):
            sum=sum+i**3
        return sum


In [14]:
series=Series(3)
print(series.add_num())
print(series.add_square())
print(series.add_qube())

6.0
1
5
5
9


In [36]:
class List:
    def __init__(self, li):
        self.li=li

    def iter_list(self):
        bikes=[]
        for bike in self.li:
            bikes.append(bike)
        return bikes

    def items(self):
        for item in self.li:
            print(item)
    def squres(self):
        squre=[]
        for item in self.li:
            squre.append(item**2)
        return squre

In [38]:
lis=List([1,2,3])
print(lis.iter_list())
print(lis.items())
print(lis.squres())


[1, 2, 3]
1
2
3
None
[1, 4, 9]


In [42]:
message =""
while message != "quit":
    message=input("enter your message or quit for exit:")
    if message !="quit":
        print(message)

dfe
good
qiw


In [43]:
pets =['dog','cat','dog','cat']
while 'cat' in pets:
    pets.remove('cat')
print(pets)

['dog', 'dog']


# Scalar Math

In [2]:
import numpy as np
arr = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
np.add(arr,1)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])